## -*- encoding: utf-8 -*-
## This file (integration_practice.sagetex.sage) was *autogenerated* from integration_practice.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('integration_practice', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
