## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file differentiation.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (differentiation.sagetex.sage) was *autogenerated* from differentiation.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('differentiation', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()

