## -*- encoding: utf-8 -*-
## This file (max_min_app.sagetex.sage) was *autogenerated* from max_min_app.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('max_min_app', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
