## -*- encoding: utf-8 -*-
## This file (curve_sketching.sagetex.sage) was *autogenerated* from curve_sketching.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('curve_sketching', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
