## -*- encoding: utf-8 -*-
## This file (Motion.sagetex.sage) was *autogenerated* from Motion.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Motion', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
