## -*- encoding: utf-8 -*-
## This file (mean_value.sagetex.sage) was *autogenerated* from mean_value.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('mean_value', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
