## -*- encoding: utf-8 -*-
## This file (taylor_series.sagetex.sage) was *autogenerated* from taylor_series.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('taylor_series', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
