## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file derivative_apps.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (derivative_apps.sagetex.sage) was *autogenerated* from derivative_apps.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('derivative_apps', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()

